import {LocaleText} from "./locale-text"
export default {
    ERROR_GENERAL: "Failed to get the information. Please contact skills developers.",
    ERROR_UNKNOWN: "Registration information can not be found. Please try again after performing the account link.",
    HELP_ACCOUNT: "Account link for registration of garbage disposal plans in this skill is required. From the account link for the card, which is displayed on the home screen of Alexa app, please set.",
    HELP_DESCRIBE: "Specify the 'Today', 'Tomorrow', 'the day after tomorrow' or 'day of the week' You can see the trash's schedule. For example, please say 'What trash on Wednesday?' ",
    HELP_BYE: "Thank you,please use again",
    HELP_NEXT_PREVIOUS: "Please specify the dates you want to know the trash's schedule.",
    NOTICE_CONTINUE: "Please say type of day or trash you want to know.",
    ASK_A_DAY: "Which date do you want to know the schedule for ?",
    NOTICE_SEND_SCHEDULE: "I sent trash's schedule that are registered. You can see information  from the card on Alexa app or display devices.",
    NOTICE_NOT_CORRESPOND: "It does not correspond to that type of trash. Please specify other trash.",
    ANSWER_LAUNCH: "Today is %s. ",
    ANSWER_NOTHING: "Nothing today. ",
    ANSWER_A_DAY: "%s1 is %s2.",
    ANSWER_NOTHING_A_DAY: "Nothing %s.",
    ANSWER_BY_TRASH: "Next %s",
    ANSWER_A_TRASH: "%s1 is %s2",
    ANSWER_DATE: "%w %m %d",
    ANSWER_NOTHING_TRASH: "%s is not registerd on trash schedule.",
    REMINDER_PERMISSION: "You need to enable reminder's permission to use this function. Please enable permission from Alexa app.",
    REMINDER_WEEK: "Which set this wekk or next week?",
    REMINDER_TIME: "what time remind?",
    REMINDER_COMPLETE: "Reminder setting complete.",
    CARD_TITLE: "registerd trash schedule",
    PURCHASE_THANKS: "Thank you for your purchase. Please try say like set reminder",
    PURCHASE_REPROMPT: "I'm sorry, one more again.",
    PURCHASE_CANCEL: "We look foward to seeing you again.",
    SEPARATOR: ",",
    CHECK_MULTIPLE: true,
    END_SEP: "and"
} as LocaleText

