import {LocaleText} from "./locale-text"
export default {
    ERROR_GENERAL:"情報の取得に失敗しました。開発者にお問い合わせください。",
    ERROR_ID_NOT_FOUND:"登録情報が見つかりません。アカウントリンクを行ってから再度お試しください。",
    ERROR_UNKNOWN: "エラーが発生しました。開発者にお問合せください。",
    HELP_ACCOUNT:"このスキルではごみ出し予定の登録のためにアカウントリンクが必要です。Alexaアプリのホーム画面に表示されたアカウントリンク用カードから、設定を行ってください。",
    HELP_DESCRIBE:"「今日」「あした」「あさって」または「曜日」を指定してゴミ出し予定を確認できます。例えば、水曜日の予定は？と聞いてください。",
    HELP_BYE:"また、使ってくださいね",
    HELP_NEXT_PREVIOUS:"ごみ出し予定を知りたい日にちを指定してください。",
    NOTICE_CONTINUE:"他に知りたい日にち、あるいはゴミの種類を言ってください。",
    ASK_A_DAY:"いつの予定が知りたいですか？",
    NOTICE_SEND_SCHEDULE:"登録されているごみ出し予定を送信しました。アレクサアプリのカード情報または画面付きデバイスから確認できます。",
    NOTICE_NOT_CORRESPOND:"そのゴミには対応していません。ゴミの種類を指定してください。",
    ANSWER_LAUNCH: "今日出せるゴミは、%s、です。",
    ANSWER_NOTHING:"今日出せるゴミはありません。",
    ANSWER_A_DAY: "%s1出せるゴミは、%s2、です。",
    ANSWER_NOTHING_A_DAY: "%s出せるゴミはありません。",
    ANSWER_BY_TRASH: "次に%sです。",
    ANSWER_A_TRASH: "%s1を出せるのは%s2",
    ANSWER_DATE:"%m月%d日 %w",
    ANSWER_NOTHING_TRASH:"%sはごみ出し予定に登録されていません。",
    REMINDER_PERMISSION: "スキルに対してリマインダー利用の許可が必要です。アレクサアプリから設定してください。",
    REMINDER_WEEK: "今週と来週、どちらのリマインダーを設定しますか？",
    REMINDER_TIME: "何時にリマインドしますか？",
    REMINDER_COMPLETE: "リマインダーをセットしました。",
    REMINDER_CONFIRM: "%s1毎日%s2にゴミ出しのリマインダーを設定します。よろしいですか？",
    REMINDER_DEFINE: "わかりました。%s1毎日%s2にゴミ出し予定をリマインドします。",
    REMINDER_CANCEL: "リマインダーの設定をキャンセルしました",
    CARD_TITLE: "登録されているごみ出し予定",
    PURCHASE_THANKS: "ご購入ありがとうございます。「リマインダーを設定して」と、言ってみてください。" ,
    PURCHASE_ALREADY_PURCHASED: "オプション機能は既に購入いただいています。「リマインダーを設定して」と、言ってみてください",
    PURCHASE_REPROMPT: "ごめんなさい。もう一度お願いします",
    PURCHASE_CANCEL: "またのご利用をお待ちしています。",
    PURCHASE_OK: "わかりました。",
    PURCHASE_UPSELL: "リマインダーでその日のゴミ出し予定をお知らせすることができます。詳しく知りたいですか？",
    SEPARATOR: "、",
    CHECK_MULTIPLE: false,
    END_SEP: ""
} as LocaleText